const alpacaData = [
  {
    id: 0,
    label: "Background",
    directory: "Background",
    selected: true,
    items: [
      { id: 1, label: "RAD 1", filename: "Rad1", selected: true },
      { id: 2, label: "RAD 2", filename: "Rad2", selected: false },
    ],
  },
  {
    id: 1,
    label: "Skin",
    directory: "Skin",
    selected: false,
    items: [
      { id: 0,  label: "Mid", filename: "mid", selected: true },
      { id: 1, label: "Pasty", filename: "pasty", selected: false },
      { id: 2, label: "Tanned", filename: "tanned", selected: false },
    ],
  },
  {
    id: 2,
    label: "Eyes",
    directory: "Eyes",
    selected: false,
    items: [
      { id: 0, label: "Glare", filename: "Glare", selected: true },
      { id: 1, label: "Eyepatch", filename: "Eyepatch", selected: false },
      { id: 2, label: "Fee Mask", filename: "fee mask", selected: false },
      { id: 3, label: "Fee Sunglasses", filename: "fee sunglasses", selected: false },
      { id: 4, label: "Mole", filename: "mole", selected: false },
      { id: 5, label: "Sus", filename: "sus", selected: false },
      { id: 6, label: "Tattoo", filename: "tattoo", selected: false },
    ],
  },
  {
    id: 3,
    label: "Head",
    directory: "Head",
    selected: false,
    items: [
      { id: 0, label: "Bald", filename: "Bald", selected: true },
      { id: 1, label: "Cool Hat", filename: "CoolHat", selected: false },
      { id: 14, label: "Kolomb", filename: "kolomb", selected: false },
      { id: 3, label: "Spiky", filename: "Spiky", selected: false },
      { id: 4, label: "Quiff", filename: "quiff", selected: false },
      { id: 5, label: "Top hat", filename: "top hat", selected: false },
      { id: 6, label: "Short Hair", filename: "short hair", selected: false },
      { id: 7, label: "Hat", filename: "hat", selected: false },
      { id: 8, label: "Long Hair", filename: "long hair", selected: false },
      { id: 9, label: "Afro", filename: "afro", selected: false }, 
      { id: 10, label: "Rascal", filename: "rascal", selected: false },
      { id: 11, label: "Radgarl", filename: "radgarl", selected: false },
      { id: 12, label: "Blondie", filename: "blondie", selected: false },
      { id: 13, label: "Dracula", filename: "dracula", selected: false },
    ],
  },
      {
    id: 4,
    label: "Mouth",
    directory: "Mouth",
    selected: false,
    items: [
      { id: 0, label: "Shaved", filename: "Shaved", selected: true },
      { id: 1, label: "Beard", filename: "Beard", selected: false },
      { id: 2, label: "Moustache", filename: "Moustache", selected: false },
      { id: 3, label: "Smile", filename: "smile", selected: false },
      { id: 4, label: "Cigarette", filename: "cig", selected: false },
      { id: 5, label: "Rad", filename: "rad", selected: false },
      { id: 6, label: "Goatee", filename: "goatee", selected: false },
    ],
  },
];

export default alpacaData;
